### ISSUE TITLE
Responsible or responsive???

### ISSUE THREAD

**Issue by AlSandro** [Serge-boro/Responsible_full_internet_Store_on_REACT#1]
re·spon·si·ble
/rəˈspänsəb(ə)l/
adjective
having an obligation to do something, or having control over or care for someone, as part of one's job or role.

re·spon·sive
/rəˈspänsiv/
reacting quickly and positively.
"a flexible service that is responsive to changing social and economic patterns"

**Comment by Serge-boro** [comment]
Понял, все переделал, спасибо
